apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
  namespace: ns-sample
  labels:
    name: gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: gateway
        app: gateway
    spec:
      containers:
      - name: gateway
        image: anthonydenecheau/k8s-gateway:k8s-gateway-master-20180712143641-19
        env:
          - name: JAVA_OPTS
            value: "-Duser.timezone=Europe/Paris -Xmx512m"
          - name: SERVER_PORT
            value: "8080"
          - name: SPRING_PROFILE
            value: "k8s"
          - name: MANAGEMENT_SECURITY_ENABLED
            value: "false"         
          - name: AUTH_USER
            valueFrom:
              secretKeyRef:
                name: authentication-credentials
                key: username
          - name: AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: authentication-credentials
                key: password
          - name: AUTH_SCOPE
            valueFrom:
              secretKeyRef:
                name: authentication-credentials
                key: scope
          - name: AUTH_GRANT
            valueFrom:
              secretKeyRef:
                name: authentication-credentials
                key: grant_type
          - name: AUTH_DEFAULT_PASSWORD_API
            valueFrom:
              secretKeyRef:
                name: authentication-credentials
                key: default_password_api
        ports:
          - name: http
            containerPort: 8080       
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            httpHeaders:
            - name: X-SCC-authentification
              value: myKeyLivenessAdministrator
          initialDelaySeconds: 30
          periodSeconds: 3
        readinessProbe:  
          httpGet:
            path: /health
            port: 8080
            httpHeaders:
            - name: X-SCC-authentification
              value: myKeyReadinessAdministrator
          initialDelaySeconds: 30
          periodSeconds: 10              
      - image: jaegertracing/jaeger-agent
        name: jaeger-agent
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - containerPort: 5778
          protocol: TCP
        command:
        - "/go/bin/agent-linux"
        - "--collector.host-port=jaeger-collector.default:14267"
